### ISSUE TITLE
Add CI/CD Checks for Pull Requests

### ISSUE THREAD

**Issue by Uh-X3L** [Uh-X3L/rETL#3]
To ensure code quality, reliability, and maintainability, set up Continuous Integration (CI) and Continuous Deployment (CD) checks for this repository. The CI/CD pipeline should automatically build, test, lint, and format the codebase on every pull request and push to the main branch.

Here’s a detailed GitHub issue you can use to track and implement CI/CD checks for your project:

---

**Title:**  
Add CI/CD Checks for Pull Requests

---

**Description:**  
To ensure code quality, reliability, and maintainability, set up Continuous Integration (CI) and Continuous Deployment (CD) checks for this repository. The CI/CD pipeline should automatically build, test, lint, and format the codebase on every pull request and push to the main branch.

---

**Acceptance Criteria:**

1. **Automated Build & Test**
   - The pipeline must run `cargo build --workspace --all-targets` and `cargo test --workspace --all-targets` on every PR and push to `main`.
   - The build must fail if any test fails.

2. **Linting and Formatting**
   - The pipeline must run `cargo clippy --workspace --all-targets -- -D warnings` to enforce linting.
   - The pipeline must run `cargo fmt -- --check` to enforce code formatting.
   - The build must fail if there are any lint or formatting errors.

3. **GitHub Actions Workflow**
   - Add a workflow file at `.github/workflows/ci.yml` with the following (or similar) content:
     ```yaml
     name: CI

     on:
       pull_request:
       push:
         branches: [ main ]

     jobs:
       build-and-test:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v3
           - name: Set up Rust
             uses: actions/setup-rust@v1
             with:
               rust-version: stable
           - name: Build
             run: cargo build --workspace --all-targets
           - name: Test
             run: cargo test --workspace --all-targets
           - name: Lint
             run: cargo clippy --workspace --all-targets -- -D warnings
           - name: Format
             run: cargo fmt -- --check
     ```

4. **Branch Protection (Optional but Recommended)**
   - Protect the `main` branch in GitHub settings.
   - Require all status checks to pass before merging.
   - Require at least one approving review before merging.

5. **Documentation**
   - Update the README.md with a section describing the CI/CD process and how contributors can ensure their code passes all checks before submitting a PR.
